log: debug

services:
  proxy-sink:
    settings:
      port: 8387
      correlation-header: tp-api-correlation-id
      mode: sink
      mocks: ./mocks

  sink:
    settings:
      uri: file:memory:?mode=memory
  
  api:
    settings:
      port: "3120"
